In [99]:
import numpy as np
import pandas as pd

In [100]:
df = pd.read_csv('./Invistico_Airline.csv')
df.head()

satisfaction   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Loyal Customer   65  Personal Travel       Eco   
1    satisfied  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Loyal Customer   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   satisfaction                       129880 non-null  object 
 1   Customer Type                      129880 non-null  object 
 2   Age                                129880 non-null  int64  
 3   Type of Travel                     129880 non-null  object 
 4   Class                              129880 non-null  object 
 5   Flight Distance                    129880 non-null  int64  
 6   Seat comfort                       129880 non-null  int64  
 7   Departure/Arrival time convenient  129880 non-null  int64  
 8   Food and drink                     129880 non-null  int64  
 9   Gate location                      129880 non-null  int64  
 10  Inflight wifi service              129880 non-null  int64  
 11  Inflight entertainment             1298

### Handling Missing values

In [102]:
(df.isnull().sum() * 100 / len(df))

satisfaction                         0.000000
Customer Type                        0.000000
Age                                  0.000000
Type of Travel                       0.000000
Class                                0.000000
Flight Distance                      0.000000
Seat comfort                         0.000000
Departure/Arrival time convenient    0.000000
Food and drink                       0.000000
Gate location                        0.000000
Inflight wifi service                0.000000
Inflight entertainment               0.000000
Online support                       0.000000
Ease of Online booking               0.000000
On-board service                     0.000000
Leg room service                     0.000000
Baggage handling                     0.000000
Checkin service                      0.000000
Cleanliness                          0.000000
Online boarding                      0.000000
Departure Delay in Minutes           0.000000
Arrival Delay in Minutes          

As 0.30 percent of data is missing in the column 'Arrival Delay in minutes'. We can replace those values.<br>
Creating a strategy to handle missing value<br> 
The duration of delay in minutes in arrival could be approximately guessed by the approximate delay in departure.

In [103]:
df[df['Arrival Delay in Minutes'].isna()]

satisfaction      Customer Type  Age   Type of Travel     Class  \
145        satisfied     Loyal Customer   21  Personal Travel       Eco   
246        satisfied     Loyal Customer   28  Personal Travel       Eco   
710        satisfied     Loyal Customer   28  Personal Travel       Eco   
736        satisfied     Loyal Customer    9  Personal Travel       Eco   
818     dissatisfied     Loyal Customer    9  Personal Travel       Eco   
...              ...                ...  ...              ...       ...   
127739     satisfied     Loyal Customer   44  Business travel  Business   
128131     satisfied     Loyal Customer   39  Business travel  Business   
128710     satisfied     Loyal Customer   45  Business travel       Eco   
129774     satisfied  disloyal Customer   49  Personal Travel       Eco   
129873     satisfied  disloyal Customer   63  Personal Travel       Eco   

        Flight Distance  Seat comfort  Departure/Arrival time convenient  \
145                4804             0                                  2   
246                1364             0                                  3   
710                1792             0                                  5   
736                1862             0                                  5   
818                1668             1                                  0   
...                 ...           ...                                ...   
127739             3431             2                                  2   
128131             1595             4                                  4   
128710              871             5                                  1   
129774             1594             5                                  4   
129873             1942             5                                  5   

        Food and drink  Gate location  ...  Online support  \
145                  0              4  ...               5   
246                  0              4  ...               4   
710                  0              3  ...               5   
736                  0              4  ...               3   
818                  1              1  ...               4   
...                ...            ...  ...             ...   
127739               3              2  ...               4   
128131               4              4  ...               5   
128710               1              1  ...               2   
129774               5              2  ...               3   
129873               4              4  ...               3   

        Ease of Online booking  On-board service  Leg room service  \
145                          5                 4                 1   
246                          2                 1                 1   
710                          5                 4                 4   
736                          3                 5                 3   
818                          4                 4                 5   
...                        ...               ...               ...   
127739                       5                 5                 5   
128131                       5                 5                 5   
128710                       5                 5                 5   
129774                       3                 1                 4   
129873                       3                 5                 2   

        Baggage handling  Checkin service  Cleanliness  Online boarding  \
145                    4                2            3                5   
246                    3                4            3                2   
710                    5                3            4                5   
736                    4                4            4                3   
818                    1                5            1                4   
...                  ...              ...          ...              ...   
127739                 5                5            5                4   
128131  

In [104]:
df.loc[df['Arrival Delay in Minutes'].isna(), 'Arrival Delay in Minutes'] = df['Departure Delay in Minutes']
df['Arrival Delay in Minutes'].isnull().sum()

0

### Feature Encoding

Encoding the Customer Type, Type of Travel and Class column in dataset.<br>
Customer Type:- Loyal Customer, disloyal customer<br>
Type of travel:- Business Travel, Personal Travel<br>
Class:- Business, Eco, Eco Plus

In [105]:
# Features
X = df.drop('satisfaction', axis=1)

# Target variable
y = df['satisfaction']

In [106]:
X = pd.get_dummies(data=X, drop_first=True)
X

Age  Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0        65              265             0                                  0   
1        47             2464             0                                  0   
2        15             2138             0                                  0   
3        60              623             0                                  0   
4        70              354             0                                  0   
...     ...              ...           ...                                ...   
129875   29             1731             5                                  5   
129876   63             2087             2                                  3   
129877   69             2320             3                                  0   
129878   66             2450             3                                  2   
129879   38             4307             3                                  4   

        Food and drink  Gate location  Inflight wifi service  \
0                    0              2                      2   
1                    0              3                      0   
2                    0              3                      2   
3                    0              3                      3   
4                    0              3                      4   
...                ...            ...                    ...   
129875               5              3                      2   
129876               2              4                      2   
129877               3              3                      3   
129878               3              2                      3   
129879               3              3                      3   

        Inflight entertainment  Online support  Ease of Online booking  ...  \
0                            4               2                       3  ...   
1                            2               2                       3  ...   
2                            0               2                       2  ...   
3                            4               3                       1  ...   
4                            3               4                       2  ...   
...                        ...             ...                     ...  ...   
129875                       5               2                       2  ...   
129876                       1               1                       3  ...   
129877                       2               2                       4  ...   
129878                       2               2                       3  ...   
129879                       3               3                       4  ...   

        Baggage handling  Checkin service  Cleanliness  Online boarding  \
0                      3                5            3                2   
1                      4                2            3                2   
2                      4                4            4                2   
3                      1                4            1                3   
4                      2                4            2                5   
...                  ...              ...          ...              ...   
129875                 4                4            4                2   
129876                 3                1            2                1   
129877                 4                2            3                2   
129878                 3                2            1                2   
129879                 5                3            3                3   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
0                                0                       0.0   
1                              310                     305.0   
2                                0                       0.0   
3                                0                       0.0   
4                                0                       0.0   
...                            .

In [107]:
# Encoding the target variable
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [108]:
le.classes_

array(['dissatisfied', 'satisfied'], dtype=object)

In [109]:
le.inverse_transform([0])

array(['dissatisfied'], dtype=object)

Encoding is like this<br>
1 :- Satified<br>
0 :- dissatisfied

### Splitting the dataset

In [110]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [111]:
X_train

Age  Flight Distance  Seat comfort  Departure/Arrival time convenient  \
18386    40             1586             3                                  3   
115613   49             1974             1                                  1   
68138    21             4373             1                                  3   
78244    54             1471             2                                  1   
34472    68             1905             4                                  4   
...     ...              ...           ...                                ...   
128106   42             1710             3                                  3   
103694   51             2148             4                                  5   
860      64             1206             1                                  0   
15795    22             1193             3                                  3   
121958   48              245             5                                  3   

        Food and drink  Gate location  Inflight wifi service  \
18386                3              3                      2   
115613               1              1                      5   
68138                3              3                      1   
78244                4              4                      3   
34472                4              1                      2   
...                ...            ...                    ...   
128106               3              3                      3   
103694               5              5                      4   
860                  1              2                      1   
15795                3              3                      1   
121958               3              3                      3   

        Inflight entertainment  Online support  Ease of Online booking  ...  \
18386                        4               4                       4  ...   
115613                       4               5                       5  ...   
68138                        1               1                       1  ...   
78244                        2               3                       3  ...   
34472                        4               2                       2  ...   
...                        ...             ...                     ...  ...   
128106                       4               4                       5  ...   
103694                       4               4                       2  ...   
860                          1               1                       1  ...   
15795                        3               5                       4  ...   
121958                       1               3                       5  ...   

        Baggage handling  Checkin service  Cleanliness  Online boarding  \
18386                  4                4            4                5   
115613                 5                3            5                4   
68138                  4                2            3                1   
78244                  4                4            4                3   
34472                  4                5            4                2   
...                  ...              ...          ...              ...   
128106                 5                4            5                4   
103694                 3                4            4                4   
860                    5                4            4                1   
15795                  4                1            4                4   
121958                 5                4            5                5   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
18386                            4                       1.0   
115613                           0                       0.0   
68138                            0                       1.0   
78244                            4                       6.0   
34472                            6                       0.0   
...                            .

In [112]:
X_train['Food and drink'].unique()

array([3, 1, 4, 5, 2, 0])

In [113]:
X_train.iloc[:, :-7]

Age  Flight Distance  Seat comfort  Departure/Arrival time convenient  \
18386    40             1586             3                                  3   
115613   49             1974             1                                  1   
68138    21             4373             1                                  3   
78244    54             1471             2                                  1   
34472    68             1905             4                                  4   
...     ...              ...           ...                                ...   
128106   42             1710             3                                  3   
103694   51             2148             4                                  5   
860      64             1206             1                                  0   
15795    22             1193             3                                  3   
121958   48              245             5                                  3   

        Food and drink  Gate location  Inflight wifi service  \
18386                3              3                      2   
115613               1              1                      5   
68138                3              3                      1   
78244                4              4                      3   
34472                4              1                      2   
...                ...            ...                    ...   
128106               3              3                      3   
103694               5              5                      4   
860                  1              2                      1   
15795                3              3                      1   
121958               3              3                      3   

        Inflight entertainment  Online support  Ease of Online booking  \
18386                        4               4                       4   
115613                       4               5                       5   
68138                        1               1                       1   
78244                        2               3                       3   
34472                        4               2                       2   
...                        ...             ...                     ...   
128106                       4               4                       5   
103694                       4               4                       2   
860                          1               1                       1   
15795                        3               5                       4   
121958                       1               3                       5   

        On-board service  Leg room service  Baggage handling  Checkin service  \
18386                  4                 4                 4                4   
115613                 5                 5                 5                3   
68138                  1                 5                 4                2   
78244                  2                 5                 4                4   
34472                  4                 5                 4                5   
...                  ...               ...               ...              ...   
128106                 5                 5                 5                4   
103694                 1                 2                 3                4   
860                    3                 2                 5                4   
15795                  4                 4                 4                1   
121958                 5                 5                 5                4   

        Cleanliness  
18386             4  
115613            5  
68138             3  
78244             4  
34472             4  
...             ...  
128106            5  
103694            4  
860               4  
15795             4  
121958            5  

[90916 rows x 15 columns]

### Feature Scaling

In [114]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train.iloc[:, :-7] = sc.fit_transform(X_train.iloc[:, :-7])
X_train = X_train.to_numpy()

In [115]:
X_test.iloc[:, :-7] = sc.transform(X_test.iloc[:, :-7])
X_test = X_test.to_numpy()
X_test

array([[ 1.28933954, -0.499042  ,  0.83699607, ...,  0.        ,
         0.        ,  0.        ],
       [-1.15710511, -0.20566812, -1.32131618, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.02485904,  1.63254824, -2.0407536 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.49590385,  1.45905804, -0.60187877, ...,  0.        ,
         1.        ,  0.        ],
       [-0.49590385,  0.31187848,  0.11755865, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.22321942,  0.58380974, -1.32131618, ...,  0.        ,
         0.        ,  0.        ]])

### Logistic Regression

In [129]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=42, max_iter=400, solver='lbfgs')
lr.fit(X_train, y_train)

LogisticRegression(max_iter=400, random_state=42)

In [130]:
y_pred_prob = lr.predict_proba(X_test)
y_pred_prob

array([[0.07234819, 0.92765181],
       [0.93947456, 0.06052544],
       [0.16985357, 0.83014643],
       ...,
       [0.92333286, 0.07666714],
       [0.64107009, 0.35892991],
       [0.12287546, 0.87712454]])

In [131]:
y_pred = lr.predict(X_test)
y_pred

array([1, 0, 1, ..., 0, 0, 1])

In [132]:
from sklearn.metrics import log_loss, accuracy_score, classification_report

print("Log Loss:", log_loss(y_test, y_pred_prob))
print("Accuracy:", accuracy_score(y_test, y_pred))

Log Loss: 0.4023129958342357
Accuracy: 0.8265578482701982


### XGBoost

In [135]:
from xgboost import XGBClassifier

In [137]:
xgbc = XGBClassifier()
xgbc.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [138]:
y_pred = xgbc.predict(X_test)

In [139]:
# print("Log Loss:", log_loss(y_test, y_pred_prob))
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9545991171337646
